# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bård N. Hovde
email: bnhovde@gmail.com
collections:
  work:
    output: true
    permalink: /my-work/:path/
description: > # this means to ignore newlines until "baseurl:"
  Hello. I’m Bård. I’m a Front-End Developer living in Southampton, UK. 
  Come on in and check out what I’ve been up to!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bardhovde.com" # the base hostname & protocol for your site
twitter_username: bardguyver
github_username:  bnhovde

# Build settings
markdown: kramdown
